---
name: "Pushbullet"
guid: "de228f12-e43e-4bd9-9fc0-2830819c3b92"
version: "4.0.0.0"
targetAbi: "10.5.0.0"
overview: "Pushbullet notification plugin"
description: >
  Get notifications via Pushbullet.
category: "Notifications"
owner: "jellyfin"
artifacts:
- "Pushbullet.dll"
changelog: >
  changelog
